FROM node:current-alpine

RUN apk update && apk add --no-cache g++ make python3

ENV NODE_ENV production

EXPOSE 8899 8099

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm i

RUN apk del g++ make python3

COPY . .

WORKDIR /usr/src/app
ENTRYPOINT [ "/usr/local/bin/node", "cli.js", "--cli" ]
