FROM node:current-alpine

EXPOSE 8899 8099

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --only=production
COPY . .

WORKDIR /usr/src/app
ENTRYPOINT [ "/usr/local/bin/npm", "run" ]
CMD [ "serve" ]