FROM node:14-slim

RUN apt-get update && apt-get install -y g++ make python3 pkg-config libpixman-1-dev libcairo2-dev libpango1.0-dev libgif-dev

ENV NODE_ENV production

EXPOSE 8899 8099

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm i

RUN apt-get -y autoremove g++ make python3 pkg-config libpixman-1-dev libcairo2-dev libpango1.0-dev libgif-dev

COPY . .

WORKDIR /usr/src/app
ENTRYPOINT [ "/usr/local/bin/node", "cli.js", "--cli" ]