name: "Build MacOS"
description: "Build MacOS dmg, Sign, Notirize and save artifact"


runs:
  using: composite
  steps:
    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Prepare building
      run: |
        npm i
        npm run dev:bastyon -- --sha=${{ steps.vars.outputs.sha_short }}
    - name: Prepare for app notarization
      run: |
        mkdir -p ~/private_keys/
        echo '${{ secrets.APPLE_API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8
        echo '${{ secrets.APPLECERT }}' | base64 -d > applecert.p12
    - name: Building
      env:
        APPLEID: ${{ secrets.APPLEID }}
        APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
        API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        API_KEY_ISSUER_ID: ${{ secrets.APPLE_API_KEY_ISSUER_ID }}
        CSC_LINK: 'file://applecert.p12'
        CSC_KEY_PASSWORD: ${{ secrets.APPLECERTPWD }}
      run: |
        npm run distm
        ls -lh ./dist/
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos
        path: ./dist/BastyonSetup.dmg
