'use strict';

module.exports = Object.freeze({
    TOR_MODE: 'TOR_MODE',
    LAST_NETWORK: 'LAST_NETWORK',
    LOCALES: 'LOCALES',
    LAST_SNI: 'LAST_SNI',
    NEXT_TIME_FOR_BRIDGES_REQUEST: 'NEXT_TIME_FOR_BRIDGES_REQUEST',
    LAST_DEFAULT_BRIDGES: 'LAST_DEFAULT_BRIDGES',
    LAST_CUSTOM_BRIDGES: 'LAST_CUSTOM_BRIDGES',
    UNREACHABLE_BRIDGES: 'UNREACHABLE_BRIDGES'
});
